[build]
  command = """
    git clone https://github.com/flutter/flutter.git -b stable
    export PATH="$PATH:`pwd`/flutter/bin"
    flutter doctor
    flutter build web --release
  """
  publish = "build/web"
